export const projectsData = {
  desc:"[UNEC]’s contribution to the region can be seen everywhere - in the many public buildings we use by day to the private dwellings we return to at night. The skilled work of our team surrounds us in thousands of expertly-crafted structures that remind us of everything we’ve achieved and all that’s yet to come.",
  items: [
    {
      title: "Al Safa One",
      image: "/assets/images/projects/prj-1.jpg",
      region: "UAE",
      category: "Residential",
      keywords: ["Al Safa One", "Residential", "Completed", "2022", "UAE"],
      client:"Dubai Electricity & Water Authority (DEWA)",
      consultant:"",
      BUA:"",
      status: "Completed",
      
    },
    {
      title: "Dragon Mall UAE",
      image: "/assets/images/projects/prj-2.jpg",
      region: "UAE",
      category: "Retail",
      keywords: ["Dragon Mall UAE", "Retail", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Al Falah School",
      image: "/assets/images/projects/prj-3.jpg",
      region: "UAE",
      category: "Education",
      keywords: ["Al Falah School", "Education", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Victoria International School Of Sharjah",
      image: "/assets/images/projects/prj-4.jpg",
      region: "UAE",
      category: "Education",
      keywords: ["Victoria International School Of Sharjah", "Education", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Canal Front Residence – Al Safa B",
      image: "/assets/images/projects/prj-5.jpg",
      region: "UAE",
      category: "Residential",
      keywords: ["Canal Front Residence Al Safa B", "Residential", "Ongoing", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Ongoing",
    },
    {
      title: "Villas Al Reeman And Infrastructure Phase II",
      image: "/assets/images/projects/prj-6.jpg",
      region: "UAE",
      category: "Residential",
      keywords: ["Villas Al Reeman Phase II", "Residential", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Fish, Meat And Vegetables Market (Kalba)",
      image: "/assets/images/projects/prj-7.jpg",
      region: "UAE",
      category: "Retail",
      keywords: ["Kalba Market", "Retail", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Elan Townhouses At Tilal Al Ghaf",
      image: "/assets/images/projects/prj-8.jpg",
      region: "UAE",
      category: "Residential",
      keywords: ["Elan Townhouses", "Tilal Al Ghaf", "Residential", "Completed", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "AL Zahia Uptown",
      image: "/assets/images/projects/prj-9.jpg",
      region: "UAE",
      category: "Mixed Use",
      keywords: ["Al Zahia Uptown", "Mixed Use", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Nakheel Mall",
      image: "/assets/images/projects/prj-10.jpg",
      region: "UAE",
      category: "Retail",
      keywords: ["Nakheel Mall", "Retail", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Silicon Central",
      image: "/assets/images/projects/prj-11.jpg",
      region: "UAE",
      category: "Retail",
      keywords: ["Silicon Central", "Retail", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Al Majdoul Tower",
      image: "/assets/images/projects/prj-12.jpg",
      region: "KSA",
      category: "Commercial",
      keywords: ["Al Majdoul Tower", "Commercial", "Completed", "2022", "KSA"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "KAFD – King Abdullah Financial District – Area 2",
      image: "/assets/images/projects/prj-13.jpg",
      region: "KSA",
      category: "Commercial",
      keywords: ["KAFD Area 2", "Commercial", "Completed", "2022", "KSA"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "AL SUHUB REST AREA",
      image: "/assets/images/projects/prj-14.jpg",
      region: "UAE",
      category: "Hospitality",
      keywords: ["Al Suhub Rest Area", "Hospitality", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Sharjah Clinical Building",
      image: "/assets/images/projects/prj-15.jpg",
      region: "UAE",
      category: "Healthcare",
      keywords: ["Sharjah Clinical Building", "Healthcare", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Nad Al Sheba 482 Villas",
      image: "/assets/images/projects/prj-16.jpg",
      region: "UAE",
      category: "Residential",
      keywords: ["Nad Al Sheba Villas", "Residential", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Sports City Residential Building",
      image: "/assets/images/projects/prj-17.jpg",
      region: "UAE",
      category: "Residential",
      keywords: ["Sports City Residential Building", "Residential", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Canal Residence",
      image: "/assets/images/projects/prj-29.jpg",
      region: "UAE",
      category: "Retail",
      keywords: ["Canal Residence", "Retail", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Canal Residence Phase II",
      image: "/assets/images/projects/prj-19.jpg",
      region: "UAE",
      category: "Residential",
      keywords: ["Canal Residence Phase II", "Residential", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Al Zahra Mosque",
      image: "/assets/images/projects/prj-20.jpg",
      region: "UAE",
      category: "Religious",
      keywords: ["Al Zahra Mosque", "Religious", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Place Tower",
      image: "/assets/images/projects/prj-30.jpg",
      region: "UAE",
      category: "Residential",
      keywords: ["Place Tower", "Residential", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "B+G+3P+18 Residential Building",
      image: "/assets/images/projects/prj-22.jpg",
      region: "UAE",
      category: "Residential",
      keywords: ["High Rise Residential Building", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Al Reem Integrated Healthcare Center",
      image: "/assets/images/projects/prj-23.jpg",
      region: "UAE",
      category: "Healthcare",
      keywords: ["Al Reem Healthcare Center", "Healthcare", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Al Sammaliya School",
      image: "/assets/images/projects/prj-24.jpg",
      region: "UAE",
      category: "Education",
      keywords: ["Al Sammaliya School", "Education", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Night Market & Boardwalk",
      image: "/assets/images/projects/prj-25.jpg",
      region: "UAE",
      category: "Retail",
      keywords: ["Night Market Boardwalk", "Retail", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "International City",
      image: "/assets/images/projects/prj-26.jpg",
      region: "UAE",
      category: "Mixed Use",
      keywords: ["International City", "Mixed Use", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Jebel Ali Water Reservoirs",
      image: "/assets/images/projects/prj-27.jpg",
      region: "UAE",
      category: "Infrastructure",
      keywords: ["Jebel Ali Water Reservoirs", "Infrastructure", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Al Furjan Villas",
      image: "/assets/images/projects/prj-28.jpg",
      region: "UAE",
      category: "Residential",
      keywords: ["Al Furjan Villas", "Residential", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Fujairah Hospital",
      image: "/assets/images/projects/prj-29.jpg",
      region: "UAE",
      category: "Healthcare",
      keywords: ["Fujairah Hospital", "Healthcare", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Deira Mall",
      image: "/assets/images/projects/prj-30.jpg",
      region: "UAE",
      category: "Retail",
      keywords: ["Deira Mall", "Retail", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    },
    {
      title: "Al Noor Mosque",
      image: "/assets/images/projects/prj-31.jpg",
      region: "UAE",
      category: "Religious",
      keywords: ["Al Noor Mosque", "Religious", "Completed", "2022", "UAE"],
      client: "Dubai Electricity & Water Authority (DEWA)",
      consultant: "",
      BUA: "",
      status: "Completed",
    }

  ]

}